### ISSUE TITLE
[Question] GitHub Actions Support

### ISSUE THREAD

**Issue by joshcampbell191** [nexB/scancode-action#1]
@tdruez Are there any plans on releasing this anytime soon or has it been abandoned? I was planning on using it in one of my projects.

**Comment by tdruez** [comment]
@joshcampbell191 an initial release of the "scancode-action" is now available.
See https://github.com/nexB/scancode-action?tab=readme-ov-file#nexbscancode-action for documentation

You can see a couple of usage examples at https://github.com/nexB/scancode-action/blob/main/.github/workflows/scan-codebase.yml and https://github.com/nexB/scancode-action/blob/main/.github/workflows/scan-package.yml
